version: '3.5'
networks:
  network:
    driver: bridge
services:
  mongo:
    image: mongo:3.7.2
    container_name: visual-management-mongo
    environment:
      MONGO_DATA_DIR: /data/db
    volumes:
      - type: bind
        source: /opt/visual-management/db
        target: /data/db
    networks:
      - network
    deploy:
      replicas: 1
  front:
    image: visual-management-front:latest
    container_name: visual-management-front
    ports:
      - target: 80
        published: 8080
    networks:
      - network
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
  server:
    image: visual-management-server:latest
    container_name: visual-management-server
    ports:
      - target: 9090
        published: 9090
    environment:
      MONGO_HOST: visual-management-mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: visual-management
    networks:
      - network
    depends_on:
      - mongo
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
