version: '3.5'
networks:
  network:
    driver: bridge
services:
  mongo:
    image: mongo:3.7.2
    container_name: visual-management-mongo
    ports:
      - target: 27017
        published: 27017
    environment:
      MONGO_DATA_DIR: /data/db
    volumes:
      - type: bind
        source: /opt/croix-rouge-portal/db
        target: /data/db
    networks:
      - network
    deploy:
      replicas: 1
